centos7安装gitlab

1、安装依赖关系

	# yum -y groupinstall 'Development Tools'
	# yum install curl policycoreutils openssh-server openssh-clients postfix

2、关闭防火墙、SeLinux
	
	# systemctl stop firewalld
	# sed -i 's@SELINUX=enforcing@SELINUX=disabled@g' /etc/sysconfig/selinux

	# firewall-cmd --permanent --add-service=http
	# systemctl reload firewalld
	# setenforce 0

3、下载安装gitlab package

	# vim /etc/yum.repos.d/gitlab-ce.repo
	
	[gitlab-ce]
	name=Gitlab CE Repository
	baseurl=https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/yum/el$releasever/
	gpgcheck=0
	enabled=1
	
	# yum -y install gitlab-ce

	脚本如果无法运行，可以直接下载下来

	# wget https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/yum/el7/gitlab-ce-9.0.5-ce.0.el7.x86_64.rpm
	# yum -y install gitlab-ce-9.0.5-ce.0.el7.x86_64.rpm

4、配置并启动gitlab
	
	# gitlab-ctl reconfigure
	# gitlab-ctl start

	# firewall-cmd --permanent --zone=public --add-port=80/tcp
	# vim /var/opt/gitlab/nginx/conf/gitlab-http.conf
		server_name mail.bjwf125.com;

5、访问并设置密码
	
	访问: http://mail.bjwf125.com     #需要设置DNS，或者修改本机hosts文件
	会提示你管理员账号密码重置
	管理员用户名默认为root

6、可能遇到的问题

	重新设置host
	# rpm 安装 gitlab.yml 路径
	# vi /var/opt/gitlab/gitlab-rails/etc/gitlab.yml
		gitlab:
  			host: xxx.xxx.xx.xxx


7、一些坑


	gitlabce的坑

	#首先祭出gitlab强大的工具
	gitlab-ctl tail; #查看当前服务器的日志,非常好用
	gitlab-ctl reconfigure; #这个命令慎用 , 它会重新创建gitlab的代码, 然后你的gitlab就会恢复默认配置了(gitlab.yml)...
	gitlab-ctl stop nginx; #停止对应的服务,由于我本机自己编译了个nginx , 所以我要吧gitlab自己打包的nginx干掉,不给启用.
	 
	#由于我自己的nginx是nobody身份启动,gitlab的目录是git账号的,然后坑爹的事情就来了 , 会出现很多权限报错:
	connect() to unix:/data1/htdocs/gitlab.mmfei.com/tmp/sockets/gitlab.socket failed (2: No such file or directory)
	connect() to unix:/var/opt/gitlab/gitlab-rails/sockets/gitlab.socket failed (13: Permission denied)
	connect() to unix:/var/opt/gitlab/gitlab-git-http-server/socket failed (13: Permission denied)
	 

	#权限问题可以用下面的一刀切的方式解决 , 虽然不好 , 但是对于小白来说 , 已经够了
	chmod 777 /usr/local/nginx.1.5.12/fastcgi_temp -R ;
	chmod 777 /var/opt/gitlab/gitlab-rails/sockets; 
	chown git:git -R /opt/gitlab/embedded/service/gitlab-rails/public; 
	chmod 777 /var/opt/gitlab/gitlab-git-http-server/; 

	##一些收集的有意义的日志和目录.....
	/opt/gitlab #holds application code for GitLab and its dependencies. 
	/var/opt/gitlab #holds application data and configuration files that gitlab-ctl reconfigure writes to. 
	/etc/gitlab #holds configuration files for omnibus-gitlab. These are the only files that you should ever have to edit manually. 
	/var/log/gitlab #contains all log data generated by components of omnibus-gitlab. 
	/var/log/gitlab/gitlab-rails/production.log; 
	/home/git/gitlab/config/gitlab.yml.example; 
	/home/git/gitlab/config/gitlab.yml; 
	/var/opt/gitlab/gitlab-rails/etc/gitlab.yml;








