version: '2'
services:
  app-nginx:
    image: nginx
    volumes_from:
      - app-php
    ports:
     - "172.31.15.245:80:80"
    command: nginx -g 'daemon off;'
    links:
      - app-php
  app-php:
    image: php-fpm-zip
    volumes:
     - /data/web/html:/usr/share/nginx/html
     - ./app-php.conf:/usr/local/etc/php-fpm.d/www.conf
     - ./app-nginx.conf:/etc/nginx/conf.d/default.conf
     - /etc/localtime:/etc/localtime:ro
